"""reviews table

Revision ID: af77eb8816ab
Revises: dcedb4e46055
Create Date: 2018-09-26 16:45:21.449290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af77eb8816ab'
down_revision = 'dcedb4e46055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('overall_rating', sa.Integer(), nullable=True),
    sa.Column('type_traveller', sa.String(length=100), nullable=True),
    sa.Column('cabin_flown', sa.String(length=100), nullable=True),
    sa.Column('seat_comfort_rating', sa.Integer(), nullable=True),
    sa.Column('cabin_staff_rating', sa.Integer(), nullable=True),
    sa.Column('food_beverages_rating', sa.Integer(), nullable=True),
    sa.Column('inflight_entertainment_rating', sa.Integer(), nullable=True),
    sa.Column('ground_service_rating', sa.Integer(), nullable=True),
    sa.Column('wifi_connectivity_rating', sa.Integer(), nullable=True),
    sa.Column('value_money_rating', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_timestamp'), 'review', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_timestamp'), table_name='review')
    op.drop_table('review')
    # ### end Alembic commands ###
